
#ifndef ES5341_DO_CFG_H
#define ES5341_DO_CFG_H

#define DO_CONFIG_IP_BASE		(0x10000)
#define DO_CHNNEL_ADDRESS_OFFSET	(0x100)

#define DO1_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x00)
#define DO1_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x04)

#define DO2_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x08)
#define DO2_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x0C)

#define DO3_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x10)
#define DO3_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x14)

#define DO4_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x18)
#define DO4_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x1C)

#define DO5_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x20)
#define DO5_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x24)

#define DO6_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x28)
#define DO6_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x2C)

#define DO7_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x30)
#define DO7_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x34)

#define DO8_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x38)
#define DO8_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x3C)

#define DO9_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x40)
#define DO9_Ref		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x44)

#define DO10_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x48)
#define DO10_Ref 	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x4C)

#define DO11_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x50)
#define DO11_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x54)

#define DO12_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x58)
#define DO12_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x5C)

#define DO13_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x60)
#define DO13_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x64)

#define DO14_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x68)
#define DO14_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x6C)

#define DO15_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x70)
#define DO15_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x74)

#define DO16_En		(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x78)
#define DO16_Ref	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x7C)

#define F_VOLT_SEC_REF	(DO_CONFIG_IP_BASE + DO_CHNNEL_ADDRESS_OFFSET + 0x80)

enum _DO {
	DO1 = 1,
	DO2,
	DO3,
	DO4,
	DO5,
	DO6,
	DO7,
	DO8,
	DO9,
	DO10,
	DO11,
	DO12,
	DO13,
	DO14,
	DO15,
	DO16,
};

void handler_do_config(unsigned int board_id, int channel, unsigned char en, unsigned char ref);
void handler_f_voit_sec_ref(unsigned int board_id, unsigned char val);
int es5341_do_cfg_init(unsigned int board_id);
void es5341_do_cfg_exit(unsigned int board_id);

#endif
